server:
  port: 8081
  
spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB
      
minio:
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: jyj
  bucket: jyj

