server:
  port: 8085
  
spring:
  application:
    name: 'springcloud-shutdown'
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: project_test
      config:
        # 配置中心地址
        server-addr: localhost:8848
        namespace: project_test
        # 配置文件格式
        file-extension: yml
        # 共享配置
#        shared-configs: 
#          - dataId: ${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}

# 健康检查配置
management:
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: '*'
    enabled-by-default: false
  server:
    address: 127.0.0.1
    port: 19999
  endpoint:
    health:
      show-details: always
      enabled: true
    shutdown:
      enabled: true
    prometheus:
      enabled: true
      
shutdown:
  waitResMaxTime: 30

