spring:
  profiles:
    active: dev
  application:
    name: spring-database
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8084

# 设置mybatis
mybatis:
  #  config-location: classpath:mybatis-config.xml
  # 注意mapper-locations这里路径的写法，需要跟idea中的保持一致
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.model
  configuration:
    map-underscore-to-camel-case: false
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
logging:
  level:
    root: info
    com.github: debug
